Update to 3.5.1
conda-forge/pyepics-feedstock pull request #41
Opened 2023-11-02 14:19 UTC by jan-janssen

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-11-02 14:21 UTC, jan-janssen commented
@conda-forge-admin, please rerender

2023-11-02 15:06 UTC, jan-janssen commented
Fixes https://github.com/conda-forge/pyepics-feedstock/pull/38

2023-11-02 15:10 UTC, tacaswell submitted a review, later dismissed

2023-11-02 15:18 UTC, tacaswell commented
This is going to be the same concern for both this PR and #42 .

We have gone through several rounds of patching pyepics on CF to not bundle the pre-built binaries that are improperly checked into the source repo and instead the pyepics conda package correctly use libca and friends from the epics conda package. 

From the patch that is removed it looks like we have been in a broken state for a while (it looks like it was trimming to "only" ship the binaries related to the platform we are on).  I think that without this patch we are back to shipping _all_ of the binaries.

I think we need to pick up a patch that purge those binaries again.

2023-11-02 15:19 UTC, tacaswell requested changes
This is shipping pre-built binaries that will be used instead of the libca from the epics-base package.

2023-11-02 15:51 UTC, tacaswell commented on recipe/build.sh
> +rm -r epics/clibs
should we do this before we install?

2023-11-02 15:53 UTC, jan-janssen commented on recipe/build.sh
> +rm -r epics/clibs
I agree

2023-11-02 19:40 UTC, jan-janssen commented
@conda-forge-admin, please rerender

2023-11-02 19:41 UTC, jan-janssen commented
@tacaswell I removed the binaries by patching the `setup.py` file. Is that fine for you? Then I can also apply it for the `3.5.2` release.

2023-11-07 18:54 UTC, jan-janssen commented
@tacaswell Can you take another look at this pull request?

2023-11-20 09:40 UTC, merged